Repository atomist/sdm-pack-fingerprint, pull requests merged in 2019-08, with the labels that each got.

#111 Remove the usage of gobal aspects map
  index.ts
  lib/checktarget/callbacks.ts
  lib/checktarget/messageMaker.ts
  lib/handlers/commands/applyFingerprint.ts
  lib/handlers/commands/broadcast.ts
  lib/handlers/commands/updateTarget.ts
  lib/machine/Aspects.ts
  lib/machine/AtomicAspect.ts
  lib/machine/fingerprintSupport.ts
  lib/machine/runner.ts
  lib/support/messages.ts
  package-lock.json
  package.json
  test/atomist.config.ts
  test/fingerprints/atomicAspect.test.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, changelog:changed

#118 Update Aspect/Fingerprint signatures
  lib/adhoc/fingerprints.ts
  lib/fingerprints/backpack.ts
  lib/fingerprints/jsonFiles.ts
  lib/fingerprints/maven.ts
  lib/fingerprints/npmDeps.ts
  lib/fingerprints/virtual-project/fileNamesVirtualProjectFinder.ts
  lib/fingerprints/virtual-project/makeVirtualProjectAware.ts
  lib/handlers/commands/applyFingerprint.ts
  lib/handlers/commands/showTargets.ts
  lib/machine/Aspect.ts
  lib/machine/AtomicAspect.ts
  lib/machine/fingerprintSupport.ts
  lib/machine/runner.ts
  lib/support/messages.ts
  lib/support/util.ts
  package-lock.json
  package.json
  test/fingerprints/atomicAspect.test.ts
  test/fingerprints/defaultTargetDiffHandler.test.ts
  test/fingerprints/virtual-project/makeVirtualProjectAware.test.ts
Labels: auto-merge-method:merge, auto-merge:on-approve, auto-rebase:on-push, changelog:changed

#132 Update runner and extension pack to understand virtual projects
  lib/checktarget/callbacks.ts
  lib/fingerprints/virtual-project/makeVirtualProjectAware.ts
  lib/machine/Aspect.ts
  lib/machine/fingerprintSupport.ts
  lib/machine/runner.ts
  test/fingerprints/atomicAspect.test.ts
  test/fingerprints/virtual-project/makeVirtualProjectAware.test.ts
  test/machine/runner.test.ts
Labels: auto-merge-method:squash, auto-merge:on-approve
