Repository atomist/sdm-pack-fingerprint, pull requests merged in 2019-07, with the labels that each got.

#82 Start getting rid of the selector
  lib/adhoc/preferences.ts
  lib/fingerprints/backpack.ts
  lib/fingerprints/jsonFiles.ts
  lib/fingerprints/maven.ts
  lib/fingerprints/npmDeps.ts
  lib/handlers/commands/applyFingerprint.ts
  lib/machine/AtomicFeature.ts
  lib/machine/Feature.ts
  lib/machine/Features.ts
  lib/machine/runner.ts
  package-lock.json
  package.json
  test/fingerprints/atomicFeature.test.ts
Labels: auto-merge:on-approve

#88 [For Discussion] Make intents SDM specific
  lib/handlers/commands/applyFingerprint.ts
  lib/handlers/commands/fingerprints.ts
  lib/handlers/commands/list.ts
  lib/handlers/commands/updateTarget.ts
  lib/machine/fingerprintSupport.ts
Labels: auto-merge-method:squash, auto-merge:on-approve

#107 Update diff handler for npm project deps
  lib/checktarget/messageMaker.ts
  lib/fingerprints/npmDeps.ts
  lib/handlers/commands/applyFingerprint.ts
  lib/handlers/commands/broadcast.ts
  lib/machine/fingerprintSupport.ts
  lib/support/messages.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, changelog:fixed
