Repository atomist/sdm-pack-fingerprint, pull requests merged in 2019-09, with the labels that each got.

#137 Add support for dynamic aspect discovery
  index.ts
  lib/machine/fingerprintSupport.ts
  lib/machine/runner.ts
Labels: changelog:added

#142 Apply target for typescript
  package-lock.json
  package.json
Labels: auto-branch-delete:on-close, auto-merge-method:squash, auto-merge:on-approve

#147 Allow for consolidation to use fingerprints created by previous consolidations. Warning: order matters.
  lib/machine/runner.ts
Labels: auto-merge:on-approve, auto-rebase:on-push
